[package]
name = "chip8_emu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.21.0"
rfd = "0.11.3"
rand = "*"
sfml = "0.20.0"
egui-sfml = "0.4.0"
rodio = "0.17.1"
